DROP SCHEMA IF EXISTS `student` ;
CREATE SCHEMA IF NOT EXISTS `student`;
CREATE TABLE IF NOT EXISTS `student`.`student` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `age` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
